controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0d936d196c0144af9, subnet-06ce812ae9ec35a91, subnet-07d602829bb14ac1f
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:891377286140:certificate/1e81c6ea-46f5-407c-9ea5-8c8771de353e
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    targetPorts:
      http: http
      https: http
  ingressClassResource:
    name: "nginx-services"
