# Values for frontend on development environment.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

namespace: development
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: ghcr.io/ddedamian/ds_challenge
  pullPolicy: Always
  tag: development
  imagePullSecretName: github-package-secret

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: "nginx-services"
    nginx.org/client-max-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  hosts:
    - host: hello.dschallenge.de # If it is used, it should be added to the Route53
      paths:
        - path: /?(.*)

  ingressClassName: "nginx-services"

enableResources: true
resources:
  requests:
    memory: "128Mi"
    cpu: "128m"
  limits:
    memory: "256Mi"
    cpu: "256m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUAverageUtilization: 80

envs:
  PORT: 80
  MY_ENV_VAR: "Im a development environment variable"
