# Default values for vault.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 0

service:
  type: NodePort
  port: 80
  targetPort: 80
  annotations: {}

enableSecurityContext: false
securityContext:
  runAsUser: 1000
  runAsGroup: 1000

enableProbes: true
readinessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 3
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

deployment:
  annotations: {}
  certs:
    enabled: false
